### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jagjordi** [outfoxxed/hy3#204]
```
[ 11%] Building CXX object CMakeFiles/hy3.dir/src/main.cpp.o
[ 22%] Building CXX object CMakeFiles/hy3.dir/src/dispatchers.cpp.o
/run/user/1000/hyprpm/jordi/src/dispatchers.cpp: In function ‘void dispatch_movefocus(std::string)’:
/run/user/1000/hyprpm/jordi/src/dispatchers.cpp:115:24: error: ‘class CWorkspace’ has no member named ‘m_hasFullscreenWindow’; did you mean ‘m_bHasFullscreenWindow’?
  115 |         if (workspace->m_hasFullscreenWindow) {
      |                        ^~~~~~~~~~~~~~~~~~~~~
      |                        m_bHasFullscreenWindow
```
I am having this error whey trying to build with hyprland version 48.1
I tried modifying the variable with `m_bHasFullscreenWindow` but then some new similar error comes: 
```
/run/user/1000/hyprpm/jordi/src/Hy3Layout.cpp:1723:36: error: ‘class CWorkspace’ has no member named ‘m_isSpecialWorkspace’; did you mean ‘m_bIsSpecialWorkspace’?
 1723 |         if (!window->m_pWorkspace->m_isSpecialWorkspace
      |                                    ^~~~~~~~~~~~~~~~~~~~
      |                                    m_bIsSpecialWorkspace
```

**Comment by wcork** [comment]
#203 has the fixes for this. I ran into that too

**Comment by jagjordi** [comment]
Thank you, I tried today again and it worked just fine!!

**Comment by outfoxxed** [comment]
A pin for 0.48.1 was missing, should be fixed.
